# Generated by Django 5.2.5 on 2025-08-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_userinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Ganders',
            field=models.CharField(max_length=15),
        ),
    ]
