# Generated by Django 5.2.5 on 2025-08-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_userinfo_ganders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Ganders',
            field=models.CharField(choices=[('Male', 'Male'), ('Other', 'Other'), ('Female', 'Female')], max_length=15),
        ),
    ]
