# Generated by Django 5.2.8 on 2025-11-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_userinfo_ganders'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('gu', 'gu'), ('hi', 'hi')], default='', max_length=15),
        ),
    ]
