# Generated by Django 5.2.4 on 2025-07-24 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, unique=True)),
                ('manger', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('none', 'none'), ('SalesManager', 'SalesManager'), ('TechicalDirectors', 'TechicalDirectors'), ('NewsDirectors', 'NewsDirectors'), ('HR', 'HR'), ('NewsAnchors', 'NewsAnchors'), ('Newsdirector', 'Newsdirector'), ('Producers', 'Producers'), ('SpecialReporters', 'SpecialReporters'), ('SeniorReporters', 'SeniorReporters'), ('JuniorReporters', 'JuniorReporters'), ('SpecialJournalists', 'SpecialJournalists'), ('SeniorJournalists', 'SeniorJournalists'), ('JuniorJournalists', 'JuniorJournalists'), ('CameraMan', 'CameraMan'), ('CameraOperators', 'CameraOperators'), ('PhotoJournalists', 'PhotoJournalists'), ('SeniorEditors', 'SeniorEditors'), ('JuniorEditors', 'JuniorEditors'), ('AudioEditors', 'AudioEditors'), ('AudioEngineer', 'AudioEngineer'), ('Scriptwriters', 'Scriptwriters'), ('Seniorwriters', 'Seniorwriters'), ('Juniorwriters', 'Juniorwriters'), ('AssignmentEditors', 'AssignmentEditors'), ('GraphicDesigners', 'GraphicDesigners'), ('BroadcastEngineer', 'BroadcastEngineer'), ('LightingTechnician', 'LightingTechnician'), ('GraphicDesigner', 'GraphicDesigner'), ('MakeupArtist', 'MakeupArtist'), ('TechnicalStaff', 'TechnicalStaff'), ('SupportStaff', 'SupportStaff')], max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('ZipCode', models.CharField(max_length=15)),
                ('OneAddress', models.TextField(max_length=350)),
                ('TwoAddress', models.TextField(max_length=350)),
                ('picture', models.ImageField(upload_to='StaffMember/')),
                ('JoinDate', models.DateField()),
                ('LeaveDate', models.DateField()),
                ('Office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='messengStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Txt', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('OthrtUserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OthrtUserName', to='staff.staffmember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='staff.staffmember')),
            ],
        ),
    ]
