# Generated by Django 5.2.4 on 2025-07-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='LeaveDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='TwoAddress',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
