# Generated by Django 5.2.4 on 2025-07-30 10:40

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffmember_leavedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='aboutme',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
