# Generated by Django 5.2.5 on 2025-08-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staffmember_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='position',
            field=models.CharField(choices=[('none', 'none'), ('Admin', 'Admin'), ('CEO', 'CEO'), ('Manager', 'Manager'), ('SalesManager', 'SalesManager'), ('TechicalDirectors', 'TechicalDirectors'), ('NewsDirectors', 'NewsDirectors'), ('HR', 'HR'), ('NewsAnchors', 'NewsAnchors'), ('Newsdirector', 'Newsdirector'), ('Producers', 'Producers'), ('Reporters', 'Reporters'), ('SeniorReporters', 'SeniorReporters'), ('JuniorReporters', 'JuniorReporters'), ('Journalists', 'Journalists'), ('SeniorJournalists', 'SeniorJournalists'), ('JuniorJournalists', 'JuniorJournalists'), ('CameraMan', 'CameraMan'), ('CameraOperators', 'CameraOperators'), ('PhotoJournalists', 'PhotoJournalists'), ('SeniorEditors', 'SeniorEditors'), ('Editors', 'Editors'), ('JuniorEditors', 'JuniorEditors'), ('Editors', 'Editors'), ('AudioEditors', 'AudioEditors'), ('AudioEngineer', 'AudioEngineer'), ('Seniorwriters', 'Seniorwriters'), ('writers', 'writers'), ('Juniorwriters', 'Juniorwriters'), ('AssignmentEditors', 'AssignmentEditors'), ('GraphicDesigners', 'GraphicDesigners'), ('BroadcastEngineer', 'BroadcastEngineer'), ('LightingTechnician', 'LightingTechnician'), ('GraphicDesigner', 'GraphicDesigner'), ('MakeupArtist', 'MakeupArtist'), ('TechnicalStaff', 'TechnicalStaff'), ('SupportStaff', 'SupportStaff')], max_length=100),
        ),
    ]
