# Generated by Django 5.2.5 on 2025-08-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_staffmember_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='picture',
            field=models.FileField(upload_to='StaffMember/'),
        ),
    ]
