# Generated by Django 5.2.7 on 2025-11-15 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0035_remove_countus_user_delete_newsblogpage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_gujarati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewsTitle', models.CharField(max_length=250)),
                ('Txt', models.TextField()),
                ('News', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.news')),
            ],
        ),
        migrations.CreateModel(
            name='News_hindi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewsTitle', models.CharField(max_length=250)),
                ('Txt', models.TextField()),
                ('News', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.news')),
            ],
        ),
    ]
