# Generated by Django 5.2.4 on 2025-07-24 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=20, unique=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('CreatedBy', models.ForeignKey(default='sorry', on_delete=django.db.models.deletion.SET_DEFAULT, to='staff.staffmember')),
            ],
        ),
    ]
