# Generated by Django 5.2.4 on 2025-07-24 09:22

import autoslug.fields
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewsTitle', models.CharField(max_length=75)),
                ('Txt', tinymce.models.HTMLField()),
                ('Image', models.ImageField(upload_to='image/')),
                ('Video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('CreatDate', models.DateField(auto_now_add=True)),
                ('JournalistsPermission', models.BooleanField(blank=True, null=True)),
                ('WritersPermission', models.BooleanField(blank=True, null=True)),
                ('EditorsPermission', models.BooleanField(blank=True, null=True)),
                ('ManagersPermission', models.BooleanField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='NewsTitle')),
                ('Collaboration', models.ManyToManyField(blank=True, to='staff.staffmember')),
                ('Editors', models.ForeignKey(blank=True, default='sorry', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Editors', to='staff.staffmember')),
                ('Journalists', models.ForeignKey(blank=True, default='sorry', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Journalists', to='staff.staffmember')),
                ('Topic', models.ForeignKey(default='sorry', on_delete=django.db.models.deletion.SET_DEFAULT, to='home.topic')),
                ('Writers', models.ForeignKey(blank=True, default='sorry', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Writers', to='staff.staffmember')),
            ],
        ),
    ]
