# Generated by Django 5.2.4 on 2025-07-24 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='multipleNewsImageAndVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('video', models.FileField(upload_to='video/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.news')),
            ],
        ),
    ]
