# Generated by Django 5.2.4 on 2025-07-24 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_multiplenewsimageandvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('NewsTopic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.topic')),
            ],
        ),
    ]
