# Generated by Django 5.2.4 on 2025-07-24 09:23

import autoslug.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_countus'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image/')),
                ('txt', tinymce.models.HTMLField()),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
            ],
        ),
    ]
