# Generated by Django 5.2.4 on 2025-07-27 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_newsblogpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Topic',
            field=models.ForeignKey(default='sorry', on_delete=django.db.models.deletion.CASCADE, to='home.topic'),
        ),
    ]
