# Generated by Django 5.2.4 on 2025-07-28 03:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_bookmarks_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='User',
            field=models.ManyToManyField(blank=True, default='', null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
