# Generated by Django 5.2.4 on 2025-07-28 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_bookmarks_user'),
        ('staff', '0002_alter_staffmember_leavedate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='followingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffMemberName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.staffmember')),
                ('User', models.ManyToManyField(blank=True, default='', null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
