# Generated by Django 5.2.4 on 2025-07-29 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_report_user'),
        ('staff', '0002_alter_staffmember_leavedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='CreatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.staffmember'),
        ),
    ]
