# Generated by Django 5.2.4 on 2025-07-29 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_topic_createdby'),
        ('staff', '0002_alter_staffmember_leavedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Editors',
            field=models.ForeignKey(blank=True, default='sorry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Editors', to='staff.staffmember'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Journalists',
            field=models.ForeignKey(blank=True, default='sorry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Journalists', to='staff.staffmember'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.topic'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Writers',
            field=models.ForeignKey(blank=True, default='sorry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Writers', to='staff.staffmember'),
        ),
    ]
