# Generated by Django 5.2.4 on 2025-07-29 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_news_editors_alter_news_journalists_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='User',
            field=models.ManyToManyField(blank=True, default='', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followingstaff',
            name='User',
            field=models.ManyToManyField(blank=True, default='', to=settings.AUTH_USER_MODEL),
        ),
    ]
