# Generated by Django 5.2.4 on 2025-07-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_bookmarks_user_alter_followingstaff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplenewsimageandvideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='multiplenewsimageandvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
