# Generated by Django 5.2.4 on 2025-07-30 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_multiplenewsimageandvideo_image_and_more'),
        ('staff', '0003_staffmember_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Editors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Editors', to='staff.staffmember'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Writers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Writers', to='staff.staffmember'),
        ),
    ]
