# Generated by Django 5.2.4 on 2025-08-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_news_editors_alter_news_writers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='EditorsPermission',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='ManagersPermission',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='WritersPermission',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
