# Generated by Django 5.2.4 on 2025-08-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_news_editorspermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='EditorsPermission',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='ManagersPermission',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='WritersPermission',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
