# Generated by Django 5.2.4 on 2025-08-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_news_editorspermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Txt',
            field=models.TextField(),
        ),
    ]
