# Generated by Django 5.2.4 on 2025-08-06 15:24

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_news_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Txt',
            field=tinymce.models.HTMLField(),
        ),
    ]
