# Generated by Django 5.2.4 on 2025-08-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_news_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
