# Generated by Django 5.2.4 on 2025-08-07 14:31

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='NewsTitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.topic'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Txt',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
