# Generated by Django 5.2.4 on 2025-08-07 14:57

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_news_newstitle_alter_news_topic_alter_news_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Image',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='NewsTitle',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='Topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='Txt',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
