# Generated by Django 5.2.4 on 2025-08-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_news_image_alter_news_newstitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='NewsTitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
