# Generated by Django 5.2.5 on 2025-08-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_news_newstitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='onlyvideo',
            field=models.BooleanField(default=False),
        ),
    ]
