# Generated by Django 5.2.5 on 2025-09-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_news_onlyvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Collaboration',
        ),
    ]
