# Generated by Django 5.2.5 on 2025-09-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_news_collaboration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countus',
            name='user',
        ),
        migrations.DeleteModel(
            name='NewsBlogPage',
        ),
        migrations.RemoveField(
            model_name='replybynews24x7',
            name='to',
        ),
        migrations.DeleteModel(
            name='Countus',
        ),
        migrations.DeleteModel(
            name='ReplyByNews24x7',
        ),
    ]
